apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: task-api
  namespace: '324817819213'
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: $name
          ports:
            - containerPort: 8080

