python_sources()

python_distribution(
    name="mydist_with_pants",
    dependencies=[
        # Dependencies on code to be packaged into the distribution.
    ],
    
	provides=python_artifact(
        name="testing_pants_distribution",
        version="2.21.0",
        description="An example distribution built with Pants.",
        author="ksajere",
        classifiers=[
            "Programming Language :: Python :: 3.7",
        ],
    ),
)
